object Versions {

    const val COMPOSE = "1.0.0"
    const val ACTIVITY_COMPOSE = "1.3.0-rc01"
    const val VIEWMODEL_COMPOSE = "1.0.0-alpha07"
    const val NAVIGATION_COMPOSE = "2.4.0-alpha05"
    const val RETROFIT = "2.9.0"
    const val GSON = "2.8.7"
    const val HILT = "2.37"
    const val KOTLIN = "1.5.10"
    const val BUILD_TOOL = "7.0.0"
    const val CORE_KTX = "1.6.0"
    const val APP_COMPAT = "1.3.0"
    const val LIFECYCLE_KTX = "2.4.0-alpha02"
    const val OKHTTP = "4.9.0"
    const val TIMBER = "4.7.1"
    const val CHUCK = "1.1.0"
    const val LIFE_CYCLE_COMPOSE = "2.3.1"
    const val MATERIAL = "1.4.0"
    const val COROUTINES = "1.3.0"
    const val ROOM = "2.3.0"
    const val HILT_NAVIGATION = "1.0.0-alpha03"
    const val WORKER = "2.5.0"

}